### ISSUE TITLE
Can't install the bundle

### ISSUE THREAD

**Issue by andie87** [MphasisWyde/ewam-advanced-framework#2]
Hi,

I try to install bundle WxWFrameworkExtended, but it return " ExtendedType cannot be installed as the bundle WFrameWork is required"

where I can get bundle WFrameWork ?

**Comment by nicolas-despres** [comment]
Hi andie,
WFrameWork is not yet on gitHub. You will have to contact wyde support for that, it is usually provided via FTP.
Regards
